-- Initial schema for the Sting Trophy Club tryout dashboard.
-- One row per player. ids are short kebab-case slugs generated by the API
-- (mirrors what the original in-browser dashboard used).

CREATE TABLE IF NOT EXISTS players (
  id              TEXT PRIMARY KEY,
  first_name      TEXT NOT NULL DEFAULT '',
  last_name       TEXT NOT NULL DEFAULT '',
  birthdate       TEXT NOT NULL DEFAULT '',
  team_bucket     TEXT NOT NULL DEFAULT 'Outside Range',
  team_label      TEXT NOT NULL DEFAULT 'Outside Range',
  coach           TEXT NOT NULL DEFAULT '',
  league          TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'Prospect',
  position        TEXT NOT NULL DEFAULT '',
  school          TEXT NOT NULL DEFAULT '',
  club            TEXT NOT NULL DEFAULT '',
  player_type     TEXT NOT NULL DEFAULT 'prospect',
  offer_sent      TEXT NOT NULL DEFAULT '',
  commitment_date TEXT NOT NULL DEFAULT '',
  follow_up       INTEGER NOT NULL DEFAULT 0,
  email           TEXT NOT NULL DEFAULT '',
  phone           TEXT NOT NULL DEFAULT '',
  contact1_name   TEXT NOT NULL DEFAULT '',
  contact1_phone  TEXT NOT NULL DEFAULT '',
  contact1_email  TEXT NOT NULL DEFAULT '',
  contact2_name   TEXT NOT NULL DEFAULT '',
  contact2_phone  TEXT NOT NULL DEFAULT '',
  contact2_email  TEXT NOT NULL DEFAULT '',
  notes           TEXT NOT NULL DEFAULT '',
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_players_team_bucket ON players(team_bucket);
CREATE INDEX IF NOT EXISTS idx_players_status      ON players(status);
CREATE INDEX IF NOT EXISTS idx_players_last_name   ON players(last_name);
